image: "python:3.5"

stages:
    - deploy

pip_deploy:
    stage: deploy
    script:
        - pip install twine wheel
        - python setup.py sdist bdist_wheel
        - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
    only:
        - tags

sourceforge_deploy:
    stage: deploy
    script:
        - pip install pysftp
        - python deploy/sourceforge.py
    only:
        - tags