image: "python:latest"

stages:
    - deploy

pip_deploy:
    stage: deploy
    script:
        - pip install twine wheel
        - python setup.py sdist bdist_wheel
        - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
    only:
        - tags

sourceforge_deploy:
    stage: deploy
    script:
        - pip install pysftp
        - python deploy/sourceforge.py
    only:
        - tags

snapcraft_deploy:
    stage: deploy
    image: "ubuntu:latest"
    script:
        - apt update
        - apt install -y snapcraft
        - snapcraft
        - snapcraft login --with $SNAPCRAFT_LOGIN_DATA
        - snapcraft push --release=stable jdtextedit_7.0_amd64.snap
    artifacts:
        paths:
            - jdtextedit_7.0_amd64.snap
    only:
        - tags
