from PyQt5.Qsci import *

def getLexerList():
    lexerList = []
    lexerList.append({"lexer":QsciLexerAVS,"name":"AVS","extension":[],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerBash,"name":"Bash","extension":[".sh"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerBatch,"name":"Batch","extension":[".bat",".batch"],"xmlapi":"batch"})
    lexerList.append({"lexer":QsciLexerCMake,"name":"CMake","extension":[".cmake"],"xmlapi":"cmake"})
    lexerList.append({"lexer":QsciLexerCoffeeScript,"name":"CoffeeScript","extension":[".coffe"],"xmlapi":"coffe"})
    lexerList.append({"lexer":QsciLexerCPP,"name":"C++","extension":[".cpp"],"xmlapi":"cpp"})
    lexerList.append({"lexer":QsciLexerCSharp,"name":"C#","extension":["cs"],"xmlapi":"cs"})
    lexerList.append({"lexer":QsciLexerIDL,"name":"IDL","extension":[".idl"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerJava,"name":"Java","extension":[".java"],"xmlapi":"java"})
    lexerList.append({"lexer":QsciLexerJavaScript,"name":"JavaScript","extension":[".js"],"xmlapi":"javascript"})
    lexerList.append({"lexer":QsciLexerCSS,"name":"CSS","extension":[".css"],"xmlapi":"css"})
    lexerList.append({"lexer":QsciLexerD,"name":"D","extension":[".d"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerDiff,"name":"Diff","extension":[".diff"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerFortran,"name":"Fortran","extension":[".f90",".f95",".f03"],"xmlapi":""})
    #lexerList.append({"lexer":QsciLexerFortran77,"name":"Fortran77","extension":[".f",".for"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerHTML,"name":"HTML","extension":[".html",".htm"],"xmlapi":"html"})
    lexerList.append({"lexer":QsciLexerXML,"name":"XML","extension":[".xml"],"xmlapi":"xml"})
    lexerList.append({"lexer":QsciLexerJSON,"name":"JSON","extension":[".json"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerLua,"name":"LUA","extension":[".lua"],"xmlapi":"lua"})
    lexerList.append({"lexer":QsciLexerMakefile,"name":"Makefile","extension":[".am"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerMarkdown,"name":"Markdown","extension":[".md"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerMatlab,"name":"Matlab","extension":[".m"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerOctave,"name":"Octave","extension":[],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerPascal,"name":"Pascal","extension":[".pp"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerPerl,"name":"Perl","extension":[".pl"],"xmlapi":"perl"})
    lexerList.append({"lexer":QsciLexerPO,"name":"PO","extension":[],"xmlapi":""})
    #lexerList.append({"lexer":QsciLexerPOV,"name":"POV","extension":[],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerPostScript,"name":"PostScript","extension":[],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerProperties,"name":"Properties","extension":[".properties"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerPython,"name":"Python","extension":[".py"],"xmlapi":"python"})
    lexerList.append({"lexer":QsciLexerRuby,"name":"Ruby","extension":[".rb",".rbw"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerSpice,"name":"Spice","extension":[],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerSQL,"name":"SQL","extension":[],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerTCL,"name":"TCL","extension":[".tcl"],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerTeX,"name":"TeX","extension":[".tex"],"xmlapi":"tex"})
    lexerList.append({"lexer":QsciLexerVerilog,"name":"Verilog","extension":[],"xmlapi":""})
    lexerList.append({"lexer":QsciLexerVHDL,"name":"VHDL","extension":[],"xmlapi":"vhdl"})
    lexerList.append({"lexer":QsciLexerYAML,"name":"YAML","extension":[".yml"],"xmlapi":""})
    return lexerList
