steps:
    check_data_files:
        image: python:latest
        commands:
            - git fetch --unshallow || true
            - pip install appstream-python
            - python ./tools/CheckDataFiles.py
