steps:
    check_data_files:
        image: python:latest
        commands:
            - git fetch --unshallow || true
            - pip install appstream-python
            - python ./tools/CheckDataFiles.py

when:
    - event: tag
    - path: ["**/*.ts", "**/*.metainfo.xml", "jdTextEdit/data/**", "tools/**", ".woodpecker/**"]
