name: jdtextedit
version: "7.2"
summary: jdTextEdit
description: |
  jdTextEdit is a powerful texteditor with a lot of features
base: core20
confinement: strict
grade: stable

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5

  jdtextedit:
    after: [desktop-qt5]
    plugin: python
    source: .
    build-packages:
      - python3
      - python3-pyqt5
      - python3-pyqt5.qtopengl
      - python3-setuptools
      - python3-pip
    stage-packages:
      - python3
      - python3-pyqt5
      - python3-pyqt5.qtopengl
      - python3-pyqt5.qsci
      - xterm

apps:
  jdtextedit:
    command: locales-launch desktop-launch $SNAP/bin/jdTextEdit
    plugs:
      - desktop
      - desktop-legacy
      - home
      - opengl
      - removable-media
      - wayland
      - x11
      - network
